# coding: utf-8

"""
    Glean Client API

    # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

    The version of the OpenAPI document: 0.9.0
    Contact: support@glean.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class EmailRequestFeedbackPayload(BaseModel):
    """
    Optional payload for feedback reporting.
    """ # noqa: E501
    comments: Optional[StrictStr] = Field(default=None, description="Additional freeform comments provided by the reporter.")
    custom_json: Optional[StrictStr] = Field(default=None, description="Arbitrary email param payloads from 3P-customer widgets. Prefer the structured fields when possible.", alias="customJson")
    image_urls: Optional[List[StrictStr]] = Field(default=None, description="Images uploaded by the user when submitting feedback", alias="imageUrls")
    issue_type: Optional[StrictStr] = Field(default=None, description="The type of issue being reported, e.g. RESULT_MISSING or OTHER for search feedback.", alias="issueType")
    query: Optional[StrictStr] = Field(default=None, description="The query the reporter tried when feedback was sent.")
    tracking_token: Optional[StrictStr] = Field(default=None, description="The tracking token of the feedback that admins can provide Glean Support to debug", alias="trackingToken")
    url: Optional[StrictStr] = Field(default=None, description="The URL the reporter was on when feedback was sent.")
    rating_key: Optional[StrictStr] = Field(default=None, description="The label of the rating that was selected when feedback was sent.", alias="ratingKey")
    __properties: ClassVar[List[str]] = ["comments", "customJson", "imageUrls", "issueType", "query", "trackingToken", "url", "ratingKey"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EmailRequestFeedbackPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EmailRequestFeedbackPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "comments": obj.get("comments"),
            "customJson": obj.get("customJson"),
            "imageUrls": obj.get("imageUrls"),
            "issueType": obj.get("issueType"),
            "query": obj.get("query"),
            "trackingToken": obj.get("trackingToken"),
            "url": obj.get("url"),
            "ratingKey": obj.get("ratingKey")
        })
        return _obj


